#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.schema=classpath:schema.sql
#spring.datasource.initialization-mode=always
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
#
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=file:src/main/resources/templates/
#
#spring.devtools.restart.enabled=true
#- ?? DB ??? url = jdbc:h2~/jdbc ??
#  - ??? ???? ? url = jdbc:h2:tcp://localhost/~/jdbc ?? ?? ??
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
